name: Auto Upload Bản tin (Huế)

on:
  schedule:
    # 03:45 ICT mỗi ngày = 20:45 UTC ngày hôm trước
    - cron: '45 20 * * *'
  workflow_dispatch:

concurrency:
  group: kttvhue-auto-upload
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PORTAL_URL: ${{ secrets.PORTAL_URL }}
      UPLOAD_URL: ${{ secrets.UPLOAD_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright python-dotenv
          playwright install --with-deps chromium

      - name: Sanity check env
        run: |
          python - <<'PY'
          import os, sys
          miss = [k for k in ["USERNAME","PASSWORD","PORTAL_URL","UPLOAD_URL"] if not os.getenv(k)]
          if miss:
              print("::error::Thiếu secrets:", ", ".join(miss))
              sys.exit(1)
          print("OK: Secrets đủ.")
          PY

      - name: Check portal reachability (HEAD)
        run: |
          set -e
          for url in "$PORTAL_URL" "$UPLOAD_URL"; do
            echo "Checking $url ..."
            curl -I --max-time 20 "$url" || echo "::warning::Không HEAD được $url (có thể chặn từ GitHub runners)."
          done

      - name: Run uploader
        run: |
          python tools/playwright_uploader.py

      - name: Upload artifact (screenshots/logs)
        uses: actions/upload-artifact@v4
        with:
          name: hue-upload-proof
          path: |
            after_upload.png
            tools/*.log
          if-no-files-found: warn
