name: Auto Upload Bản tin (Huế)

on:
  schedule:
    # 03:45 ICT mỗi ngày = 20:45 UTC ngày hôm trước
    - cron: '45 20 * * *'
  workflow_dispatch:

concurrency:
  group: kttvhue-auto-upload
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    env:
      USERNAME: ${{ secrets.USERNAME }}       # THUE
      PASSWORD: ${{ secrets.PASSWORD }}       # Hue2024@
      PORTAL_URL: ${{ secrets.PORTAL_URL }}   # http://222.255.11.117:8888/Login.aspx
      UPLOAD_URL: ${{ secrets.UPLOAD_URL }}   # http://222.255.11.117:8888/UploadFile.aspx

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (Playwright + Chromium)
        run: |
          python -m pip install --upgrade pip
          pip install playwright python-dotenv
          playwright install --with-deps chromium

      - name: Sanity check env
        run: |
          python - <<'PY'
          import os, sys
          miss = [k for k in ["USERNAME","PASSWORD","PORTAL_URL","UPLOAD_URL"] if not os.getenv(k)]
          if miss:
              print("::error::Thiếu secrets:", ", ".join(miss))
              sys.exit(1)
          print("OK: Secrets đủ.")
          PY

      - name: Ensure PDFs exist under bantin/
        run: |
          ls bantin/*.pdf >/dev/null 2>&1 || (echo "::error::No PDFs in bantin/"; exit 1)

      - name: Check portal reachability (HEAD)
        run: |
          set -e
          for url in "$PORTAL_URL" "$UPLOAD_URL"; do
            echo "Checking $url ..."
            curl -I --max-time 20 "$url" || echo "::warning::Không HEAD được $url (có thể chặn GitHub runners)."
          done

      - name: Run uploader (retry tối đa 3 lần, cách nhau 10 phút)
        shell: bash
        run: |
          set -euo pipefail
          max=3
          gap_sec=$((10*60))   # 10 phút
          for attempt in $(seq 1 $max); do
            echo "===== Attempt $attempt/$max ====="
            if python tools/playwright_uploader.py; then
              echo "✅ Thành công ở lần $attempt — dừng retry."
              ts=$(date +%Y%m%d_%H%M%S)
              [ -f after_upload.png ] && cp -f after_upload.png "after_upload_attempt_${attempt}_$ts.png"
              [ -f tools/uploader.log ] && cp -f tools/uploader.log "tools/uploader_attempt_${attempt}_$ts.log"
              exit 0
            else
              echo "❌ Thất bại lần $attempt"
              ts=$(date +%Y%m%d_%H%M%S)
              [ -f after_upload.png ] && cp -f after_upload.png "after_upload_attempt_${attempt}_$ts.png" || true
              [ -f tools/uploader.log ] && cp -f tools/uploader.log "tools/uploader_attempt_${attempt}_$ts.log" || true
              if [ "$attempt" -lt "$max" ]; then
                echo "⏳ Chờ 10 phút rồi thử lại..."
                sleep "$gap_sec"
              fi
            fi
          done
          echo "🚫 Hết số lần thử, vẫn thất bại."
          exit 1

      - name: Upload artifact (screenshots/logs)
        uses: actions/upload-artifact@v4
        with:
          name: hue-upload-proof
          path: |
            after_upload*.png
            tools/*.log
            tools/uploader_attempt_*.log
          if-no-files-found: warn
